SELECT * FROM Employee;

SELECT EMPNO,SALARY FROM Employee;

SELECT NAME, avg(SALARY) FROM Employee GROUP_BY EMP_NAME;

SELECT EMPNO FROM Employee;

SELECT count(distinct EMPNO) FROM Employee;

SELECT SALARY FROM Employee GROUP_BY EMP_NAME;

SELECT SALARY FROM Employee WHERE SALARY>120000;

SELECT NAME FROM Employee ORDER_BY EMP_NAME desc;

SELECT * FROM Employee WHERE NAME = 'Amit' AND SALARY GREATER THAN 50000